### ISSUE TITLE
pickle5 PicklingError

### ISSUE THREAD

**Issue by Dixit91** [sjtu-marl/malib#58] opened 2023-01-08 11:14 UTC
**Environment:**
    1. Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )
    2. conda 4.5.4

**command:** 
    1. conda create -n malib python==3.7 -y
    2. conda activate malib
    3. ./install.sh
    4.  python examples/run_psro.py

**bug report:**

KeyError: (<class 'RuntimeError'>, ('numba jitted function aborted due to unresolved symbol',), None)
During handling of the above exception, another exception occurred:
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:
pickle5.pickle.PicklingError: Could not pickle object as excessively deep recursion required.

[1.log](https://github.com/sjtu-marl/malib/files/10368227/1.log)

**Comment by KornbergFresnel** [comment] 2023-01-09 13:05
@Dixit91  It seems to be the issue of serialization of numba. I've tested the latest malib on Linux5.4.0-131-generic, and cannot reproduce this issue. Further investigation is required, or you can check whether numba can cooperate with ray>=1.13 on RedHat Linux version 3.10.0-1160.71.1.el7.x86_64.

**Comment by KornbergFresnel** [comment] 2023-02-15 06:41
Resolved with using Python3.8. Readme has been udpated

**Closed by KornbergFresnel** 2023-02-15 06:41 UTC
